version: '3.7'
networks:
  kafka:
    driver: overlay
services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    networks: kafka
    mode: global
    constraint: node.labels.zoo==1
    ports:
     - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    networks: kafka-net
    mode: global
    constraint: node.labels.kafka==1
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://ec2-3-21-198-203.us-east-2.compute.amazonaws.com:9092
    volumes:
      - 'kafka2_data:/bitnami'
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:2'
    networks: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://ec2-3-21-198-203.us-east-2.compute.amazonaws.com:9093
    volumes:
      - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:2'
    networks: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://ec2-13-58-140-213.us-east-2.compute.amazonaws.com:9094
    volumes:
      - 'kafka3_data:/bitnami'
    depends_on:
      - zookeeper

volumes:
  kafka_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local
